### PR TITLE
WIP: real-time collaboration

### PR DESCRIPTION
**Pull request by tangjeff0**
Some conversation on Discord: https://discord.com/channels/708122962422792194/714804822909517935/808779175413678171

Value:
1. Requested by our potential first enterprise customer
2. Enables Athens team to use a db together to share knowledge

Specs
- uses filesystem to communicate real-time changes
	- therefore requires a filesync service like Dropbox or Syncthing
- on startup, read `db/path/index.transit`
- on change, update in-memory db and write a log to `db/path/tx-logs/{timestamp}-{os-username}.log`
	- edge case: same os-username, different computers/clients
- watch `db/path/tx-logs/`. on new log from another username, update in-memory db
- when no new logs detected for 60 seconds, write `{timestamp}-index.transit.bkp` file and copy to `index.transit`, same as current saving flow
	- but when the new db is written to client A and then db is synced, client B believes that `index.transit` is wrong, and overwrites the changes that just happened

### CODE REVIEW

**Comment by jeroenvandijk** [comment]
> edge case: same os-username, different computers/clients

What about creating a unique id (uuid) the first time Athens starts and use that to identify the client? The username could be added for debugging purposes. If the string is too long you could hash the uuid e.g. `jeroen-923flsaf`.

**Comment by tangjeff0** [comment]
After working on this implementation deeply for a week, I've concluded that it's too difficult at this time to resolve conflicts with atomic append-only tx logs over a synced filesystem.

- Each client can have differing tx logs, which might not be valid transactions on another db.
- Each client can also write to `index.transit`, which is currently the final source of truth
- But each client can also have it's own in-memory db state, which can differ from filesystem db state.

This is `n*3` different states. There are edge cases where each state could be considered "authoritative": the tx log, the in-memory db, or the fs db.

That's not to say tx logs are impossible as an eventual solution, but that deeper design is needed to implement a solution a feel is safe for users. Roam has notably has the worst data loss and availability issues it's had in over a year, in the past 2 weeks.

I do believe stability and longevity should be prioritized when it comes to user data.

**Comment by jeroenvandijk** [comment]
I can imagine this is a hard problem to tackle. You mention:


> Each client can have differing tx logs, which might not be valid transactions on another db.

Do you have examples of invalid transactions?


> There are edge cases where each state could be considered "authoritative"

I'm curious to learn more about these edge cases. 

I'm also wondering if `index.transit` could be treated as a cached materialized view fo the tx-logs and only be used as a cache during the initialisation of Athens. It would then be updated every X transactions

**Comment by tangjeff0** [comment]
> Do you have examples of invalid transactions?

The way it was written in this branch, we save the final raw output datoms, then transact them to other clients on read. However, when raw datoms are directly transacted, [they are "trusted" and not validated](https://cljdoc.org/d/datascript/datascript/1.0.3/api/datascript.core#init-db). Therefore if an entity id exists on one db but not the others, an error is thrown. Conor told me to always use `:block/uid` for transactions over websockets, which implies entity ids can get out of sync.

Example of a transaction:

```
[#datascript/Datom [100 :block/order 1 536893313 true]
 #datascript/Datom [100 :block/uid "0d0891ed2" 536893313 true]
 #datascript/Datom [100 :block/open true 536893313 true]
 #datascript/Datom [100 :block/string "" 536893313 true]
 #datascript/Datom [100 :block/children 38041 536893313 true]]
```

> I'm curious to learn more about these edge cases.

1. Filesystem is correct store: on startup
2. Append-log is correct store: when a client reads an append log from another client
3. In-memory  is correct store: when a user writes to their application

Finally, you can run two instances of Athens on two different computers with the branch `tangjeff0:append-log`, and try making multiple changes at the same time to test some of this behavior out. @jelmerderonde

**Comment by tangjeff0** [comment]
@tomisme mentioned https://braid.news/ here

**Pull request closed without merging**
