### PR TITLE
fix block move after last block

### PR DESCRIPTION
**Pull request by sid597**

### CODE REVIEW

**Comment by sid597** [comment]
Tests to perform

- [x] as first block
- [x] as the last block
- [x] as the first child of a block
- [x] as the sibing of the parent

I think other drag and drop result in one of the above cases

**Comment by neotyk** [comment]
@sid597 can we get some tests with it?

**Comment by sid597** [comment]
> @sid597 can we get some tests with it?

yes

**Review by neotyk — APPROVED** [review]
LGTM

**Pull request merged**
