### PR TITLE
moving docs to handbook

### PR DESCRIPTION
**Pull request by jsmorabito**
deleted code of conduct, contributing, vision, and governance.md and added them to handbook repo. also added architecture.md

### CODE REVIEW

**Comment by phrohdoh** [comment]
What are we doing to point people to the handbook?
If they find the main repo not containing any of this they may not realize there are procedures/requirements/etc which _may_ result in a growing noise:signal ratio or may steer someone away from Athens due to perceived lack of process/organization.

CONTRIBUTING.md, and perhaps others, are given special treatment by GitHub (it calls these files out during the PR/issue creation flow, for example) and we'd be losing that on the main repo by deleting them entirely.

**Comment by tangjeff0** [comment]
What's the high level architecture here again @jsmorabito ? Product docs in this repo, project docs in handbook?

**Comment by jsmorabito** [comment]
> What's the high level architecture here again @jsmorabito ? Product docs in this repo, project docs in handbook?

yes

> What are we doing to point people to the handbook?
I've added links in the documentation channel and the welcome channel and made a note on #509 to make these accessible from there

@phrohdoh thank you for pointing out the utility of the contributing doc for the issue/creation flow. I will add a contributing.md with gitbook and if you or anyone else can think of which other github enhanced .mds we should have please comment

**Comment by tangjeff0** [comment]
What all needs to be in place before we merge this? @jsmorabito

**Comment by jsmorabito** [comment]
> What all needs to be in place before we merge this? @jsmorabito
short answer: everything is in place except we might need to change "doc" folder to "docs" long answer below:

image
taryns right about the issue creation/pr giving special treatment to contributing.md and code of conduct.md so i added those to our doc folder in the athens repo which means theyre in both the handbook and athens doc folder (with identical content) so ive made a note to myself to divide up the content appropriately between the two so theres less redundancy/confusion

image
on this page they say these files (contributing/code of conduct) can be in a docs folder to get recognized so we might want to change our "doc" folder to "docs" to make sure this happens

**Comment by tangjeff0** [comment]
Keep:

- README.md
- CHANGELOG.md
- LICENSE

Handbook:

- CODE_OF_CONDUCT.md
- GOVERNANCE.md -> WIP

Website:
- Privacy Policy
- Terms of Service

**Comment by jsmorabito** [comment]
ready to merge

**Pull request closed without merging**
