### PR TITLE
doc: Create a Contributor Covenant Code of Conduct

### PR DESCRIPTION
**Pull request by seekanddefine**
Our Github community profile is incomplete without this document and a template is provided by Github. This is the template with researchathens@gmail.com added for the contact. https://github.com/athensresearch/athens/community

### CODE REVIEW

**Comment by tangjeff0** [comment]
We have had a CoC. It got migrated to Handbook. Should we put it back here?

**Review by tangjeff0 — CHANGES_REQUESTED** [review]
We have a CoC. It got migrated to Handbook I think. Should we just use that one?

**Comment by seekanddefine** [comment]
The Code of Conduct that previously existed was not a legal document. It was guidelines on how to participate in Discord.

**Comment by tangjeff0** [comment]
@seekanddefine the CoC mentions Discord but it applies to the community in general. https://athensresearch.gitbook.io/handbook/main-stuff/welcome/code-of-conduct

**Comment by tangjeff0** [comment]
Seems stale. Closing. Can re-open if work resumes on this

**Comment by seekanddefine** [comment]
The previous CoC had the following sections:

*    Values-some quotes
*   Athens Discord-invite, kick, auto-moderate
*   Discord Official-their privacy policy and terms of service

It said nothing about what behaviors were acceptable in a black and white way. There are Athens contributors who are not active on Discord. The policy must detail behaviors that must be prevented including workplace discrimination and business resources for personal use. 

I rewrote the CoC because this is inadequate and puts Athens at risk with greater liability. Outcome Health, a startup with 500 million, valued at 5.5 billion, was sued by investors because it was lying to customers. It ended with an SEC investigation and an updated code of conduct. You can't assume people will have the same ethics you do. A company of any size needs a CoC and it is legally mandated for public companies. This is the first document new employees should review and agree to, many require a physical signature. This is about risk mitigation and compliance, but also marketing and attracting people who are aligned with a commitment to high standards and right conduct.

**Comment by tangjeff0** [comment]
Thank you for elaborating on what was missing. This seems like an important document for Athens. Merging in now. Will want to consolidate both this CoC and the other eventually. cc @joelhans

**Pull request merged**
