### PR TITLE
Page-level presence

### PR DESCRIPTION
**Pull request by filipesilva**

### CODE REVIEW

**Comment by neotyk** [comment]
LGTM

**Review by shanberg — APPROVED** [review]

**Comment by tangjeff0** [comment]
1. [Not sure if this is a known issue.](https://athens-git-fork-filipesilva-presence-details-athens-research.vercel.app/?path=/story/components-avatar--on-blocks). I'm guessing this can be addressed in a future PR.

image

**Comment by filipesilva** [comment]
@tangjeff0 it's known, some of the in-concept elements (like blocks) have erros like this on storybook. Avatar is being used right now but that particular story uses blocks as well. IIRC @shanberg was going to fix those comps that error on storybook.

**Comment by tangjeff0** [comment]
Great work @filipesilva @shanberg !

**Comment by tangjeff0** [comment]
Can you provide some context on why Babel was imported in this PR? Just curious @filipesilva

**Comment by filipesilva** [comment]
@tangjeff0 we were already using babel, but with a different config (.babelrc instead of babel.config.js). Trying to use to use the more complex presence components revealed issues with the babel setup that required a change in config type (to add functions) and change in configuration items (to fix the issues proper).

For futher context, storybook itself also uses babel for TS compilation, and shadow-cljs uses babel for node_modules compilation from ESM to CJS.

**Comment by shanberg** [comment]
> [Not sure if this is a known issue](https://athens-git-fork-filipesilva-presence-details-athens-research.vercel.app/?path=/story/components-avatar--on-blocks). I'm guessing this can be addressed in a future PR.
> 
> image

I do plan to fix, just lower priority.

**Pull request merged**
