### PR TITLE
rfct: use goog dom function

### PR DESCRIPTION
**Pull request by fnumatic**

### CODE REVIEW

**Comment by fnumatic** [comment]
> Should we do this globally? Many files use `getElementById`

I'm on it

**Comment by tangjeff0** [comment]
Okay, could just update this PR, don't need to close :)

**Comment by fnumatic** [comment]
yeah know. family interference

**Comment by fnumatic** [comment]
curious, on athena.cljs L296 there is a call of set! with one param ???

**Comment by tangjeff0** [comment]
That clears the input text @fnumatic

**Pull request merged**
