### PR TITLE
fix(auto-complete): pressing [[,(( and enter works better. close #1214, #1220

### LINKED ISSUE #1214: Block search after wrapping `((` around selection is buggy
### Discussed in https://github.com/athensresearch/athens/discussions/1204

<div type='discussions-op-text'>

<sup>Originally posted by **datokrat** May 21, 2021</sup>
# Problem

Select some text, type `((`. This opens the block search panel. Select a block. One would expect that this results in a block reference to the selected block. However, in BETA-80, nothing happens (except that some characters are unselected), while in BETA-82, instead of a block reference, we get just `((`.

As an aside (which should probably get a separate bug report), after selecting text and then typing `((`, sometimes no item is selected at all, so that pressing ENTER leads to an error message that the selected index is still `nil`. It seems to be reproducible in the following way: Create a new block and then do the above as the first thing you do. I suspect that there is some problem with the local state of the block. After re-opening the page, this state is flushed and the bug occurs at pre-existing nodes again.

I believe the former bug to be a bit more severe.

# Demo

Here is a recording demonstrating the two bugs (first the former, then the latter) in the [github.io instance](https://athensresearch.github.io/athens/).

[https://www.loom.com/share/97e1ab3b9d8c40348b5ae1b661a0aa84](https://www.loom.com/share/97e1ab3b9d8c40348b5ae1b661a0aa84)

# Athens version and environment

Tested mainly in the browser (BETA-80 and BETA-82), but this also occured to me in my native BETA-80 running on Linux.

# A side remark

My main use case for "write text, select text, type `((`" stems from the performance problems with the block search (see #756). I noticed that searching lots of blocks is only slow when the resulting list of blocks is very long. However, when I write a very specific search query and then surround it with `((`, the search is very fast, even in older versions of Athens. This puzzles me a bit, since the #756 performance problems seem to be fixed by optimizing the search queries. I'm puzzled why the very specific search queries have been blazing fast even before this fix.

# Fix

I have a [fix](https://github.com/datokrat/athens/tree/fix-autocomplete) for the first bug, which also contains some refactoring of `auto-complete-inline`. Since this isn't an issue yet, I did not create a PR. </div>

### PR DESCRIPTION
**Pull request by datokrat**
See #1214.

Already editing `auto-complete-inline`, I noticed that the arity-overloaded contains duplicated code, one for each signature. The duplication was removed.

There is more code duplication in the arity-overloaded methods of the same file, which I can refactor, too, if this is wanted.

(Edit: I replaced "multimethod" by "arity-overloaded method")

### CODE REVIEW

**Comment by tangjeff0** [comment]
Hi @datokrat, I love how this PR is largely documentation and refactor of existing code.

A small correction: [multimethod](http://clojure-doc.org/articles/language/polymorphism.html#extending-protocols-for-core-clojure-data-types) and [arity-overloading](https://riptutorial.com/clojure/example/11372/parameters-and-arity) are conceptually similar, but in Clojure there are in fact two separate constructs.

**Comment by datokrat** [comment]
I added a bit more analogous refactoring and fixed a minor bug I found when I stumbled upon a discrepancy of the two implementations of `auto-complete-slash` I wanted to merge. The bug was that when `Block Embed` was selected using mouse, no block search panel would appear.

**Comment by datokrat** [comment]
I noticed that there are some more places in `textarea_keydown` where undo might fail. I'll update them, too. Until then, I make this a draft.

**Comment by datokrat** [comment]
The `deps-check` was fixed in #1220, I hope this is fine :)

**Review by tangjeff0 — CHANGES_REQUESTED** [review]
Hey @datokrat I'm not sure this works. Am I demo'ing this right? https://www.loom.com/share/fe8950585d6f4650ba493e1c576ff0c0

**Comment by datokrat** [comment]
Yes, that's right. I'm sorry. I did some further refactoring an forgot to test this edge case.

So, just for protocol, these cases should work now, I tried it again:

- hashtag completion
- ``[[`` and ``((`` completion without selected text
- ``[[`` and ``((`` completion with selected text
- `/` completion
- undo in all of these cases.

**Comment by datokrat** [comment]
I merged PR #1234 into this one. Selection and autocompletion both work now:

https://www.loom.com/share/7cd8671b3d2b4cbb8d29ac0ac78d04f4

What's left is another update of the re-frame-10x dependency from 1.1.0 to 1.1.1 :rocket: I'm currently doing a full rebuild to ensure the version bumb doesn't break anything.

**Comment by tangjeff0** [comment]
Don't worry about versioning. Clojure deps never breaks and it's a patch!

**Review by tangjeff0 — APPROVED** [review]
You are a refactor beast! 

Deleted two `println`s for you.

Next up, if you want to continue in this area, is fixing `update-query` so it's defined on caret position rather than keybindings #607

**Pull request merged**
