### PR TITLE
Code style refactoring

### PR DESCRIPTION
**Pull request by Bardia95**
Fixed a type in one of the comments
Conformed hiccup-producing functions to best practices code style for readability

### CODE REVIEW

**Comment by Bardia95** [comment]
@jeroenvandijk can you explain me the style and carve steps in the build checks? Not sure how/why they're failing

**Comment by jeroenvandijk** [comment]
@Bardia95 Don't worry about `carve`. Let's fix that separately. carve is looking for unused vars and there is a carve_ignore file for the vars that need to stay

I'm a bit worried about this pull request. There are still too many changes. You are mixing formatting with code style (:class vs the dot-notation). For a reviewers point of view this makes it really hard. Since there are some many changes, please focus on one type of change.

**Comment by Bardia95** [comment]
> I'm a bit worried about this pull request. There are still too many changes. You are mixing formatting with code style (:class vs the dot-notation). For a reviewers point of view this makes it really hard. Since there are so many changes, please focus on one type of change.

I'm honestly confused. Am I supposed to make one line change per commit?

**Comment by Bardia95** [comment]
These are such minor changes and they don't change the functionality of the code whatsoever. So I don't get why its hard for you to review this? Each commit only has to do with a single function. Each commit only deals with a specific problem with the code.

**Comment by Bardia95** [comment]
And I don't get it, if I see a small typo, what am I supposed to do? Make a separate pull request for the typo??

**Comment by Bardia95** [comment]
Btw @jeroenvandijk I just went through each commit, and it took me less than 5 minutes to see review all the changes, don't see why its problematic at all.

**Comment by tangjeff0** [comment]
@Bardia95 Please give @jeroenvandijk a moment to respond. You made 5 comments in a row with minutes between each comment. In #60 you said:

> Can you guys code review my pull request when you get a chance? Be as critical as you want, I want as much feedback as you are willing to give me.

Trust that we will respond and the feedback is constructive and intentional. If not, it will be worked out. @jeroenvandijk has been developing Clojure for 7 year and is a CTO. Your tone in these comments is not coming off as receptive to feedback. Am I reading this incorrectly?

**Pull request closed without merging**
