### PR TITLE
fix: bugs introduced by new parser

### LINKED ISSUE #1015: fix: bugs and clarify behavior introduced by #957
- [X] multiple block refs #1012
- [ ] allow for spaces inside image #1013
- [ ] multiple LaTeX fragments, e.g. `$$a$$ and $$b$$` #1017
- [ ] no need for spaces around block refs, e.g. `.((c1c466055))`
- [ ] this LaTeX should work (yifan) `$$G, \mu$$ and Poisson's ratio $$\nu$$`

### PR DESCRIPTION
**Pull request by neotyk**
Fix #1015 

## LaTeX

Multiple LaTeX fragments in a block: `$$a$$ some text $$another \LaTeX fragment$$`
`$` allowed in LaTeX: `$$a\raisebox{0.25em}{$b$}c$$`

## Block refs in text

No need for spaces around block references: `text((block-id))text`

## MD Links & Images URL can have spaces

Common case with local FS links: `[link text](/url/with spaces)` & `[link text](/with spaces "and link title")`

## Presserve newlines

Now when you Shift+Enter in a block this newline is preserved.

### CODE REVIEW

**Comment by tangjeff0** [comment]
ready for review?

**Comment by neotyk** [comment]
it's just one bullet from #1015 
This fix won't change, but we need more.

**Comment by neotyk** [comment]
@tangjeff0 now it's ready for review

**Comment by sawhney17** [comment]
Error still occurs, although a different error now. Image links, with spaces, at first, weren't even recognized as links. Now, they are recognized but fail to render.

**Pull request merged**
