### PR TITLE
fix(contentarea): hide multiline text in contentarea

### LINKED ISSUE #613: Hover over block with hyperlinked text expands block
**Problem**
Hovering over a block with hyperlinked text where the link address is larger than the text in the block will expand the block div(?) 

**Screenshots/Demo**
https://www.loom.com/share/4caa10ac843b44c5a6bf2b6e3df902b1

**Athens Version**
1.0.0-BETA.33

### LINKED ISSUE #1131: Hovering over multi line MD links creates ghosting effect
**Problem**
For links that are multiple lines but are shortened to only fit on one line like this:

`[https://pubmed.ncbi.nlm.nih.gov/30839...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbTlLRm9meWRnMDdrRTgxMmpZZmhrMjlrTWNtZ3xBQ3Jtc0ttQVBzbUFRY1B3M1dPUVByeHlpLU8zZ0xSbWF2YXVmcEU4em9jMDFQNjVaTjRtWFZHQ292UExKQXBBZnVhU1RmWDJVMG9xcjhhaWpBY3ZtLVdLSHh5VlJOMUUtVmJuZW4yRUpWaFR2UHdNc3Zva1BVVQ&q=https%3A%2F%2Fpubmed.ncbi.nlm.nih.gov%2F30839054%2F)`

For these links, that should fit on one line, a weird ghosting effect occurs with the bullet box expanding upon hover. 

Apologies for the vague description, not sure how to describe it, watch the video
**Screenshots/Demo**
https://www.loom.com/share/398d35a9fb8149238f51c644f9790b7f
**Athens Version**
Athens Beta 78

### PR DESCRIPTION
**Pull request by ozimos**
close #1131 by setting the default line-height on contentarea to 0. 

close #613 (duplicate)

### CODE REVIEW

**Comment by tangjeff0** [comment]
@shanberg review?

**Review by shanberg — CHANGES_REQUESTED** [review]
Unfortunately this approach causes the hidden textarea to be inaccessible to the mouse, so it doesn't capture the insertion point when you click into text.

Screen Recording 2021-05-18 at 7 14 39 PM

**Review by tangjeff0 — CHANGES_REQUESTED** [review]
Clicking should place caret in approximately the right location.

**Comment by ozimos** [comment]
caret position in textarea fixed. Also fixed the flicker on textarea blur

**Comment by shanberg** [comment]
I'm impressed with your fixes here @ozimos. I'd sort of assumed we'd hit a local maximum with the textarea-based UX, but clearly it can still improve.

Demo gifts attached. It’s maddening to see both animations together so I've linked them instead.

[Before demo](https://user-images.githubusercontent.com/98312/118893487-7e80a300-b8d0-11eb-8bcc-0294f88d9689.gif)
[After demo](https://user-images.githubusercontent.com/98312/118893512-87717480-b8d0-11eb-8050-6e89c3e82ad8.gif)

**Review by shanberg — APPROVED** [review]

**Review by tangjeff0 — APPROVED** [review]

**Pull request merged**
