### PR TITLE
fix(ci): ignore windows Sentry variable

### PR DESCRIPTION
**Pull request by tangjeff0**
Curious if you know how to interpolate variables from the Windows command line @juniusfree 

In linux/mac it is:

`lein run -m shadow.cljs.devtools.cli --npm compile main renderer --config-merge "{:closure-defines {athens.core/SENTRY_DSN \"${SENTRY_DSN}\"}}"`

For Windows, I tried unsuccessfully to do:

`lein run -m shadow.cljs.devtools.cli --npm compile main renderer --config-merge "{:closure-defines {athens.core/SENTRY_DSN \"%SENTRY_DSN%\"}}"`

### CODE REVIEW

**Comment by juniusfree** [comment]
@tangjeff0 I don't know but I'll try. What should happen with this command?

**Comment by tangjeff0** [comment]
Basically, how do we run a Windows shell command while using an environment variable in a quoted string?

I know how to do this this in Linux and Mac, but not Windows.

https://github.com/tangjeff0/athens/runs/1857971968?check_suite_focus=true
image

https://github.com/tangjeff0/athens/runs/1858096010?check_suite_focus=true
image 

@juniusfree

**Comment by juniusfree** [comment]
@tangjeff0 Can you try this? Remove the quotations between `%SENTRY_DSN%`

`lein run -m shadow.cljs.devtools.cli --npm compile main renderer --config-merge "{:closure-defines {athens.core/SENTRY_DSN %SENTRY_DSN%}}"`

**Comment by juniusfree** [comment]
Oh sorry. It should be in a quoted string. I'll check again.

**Comment by juniusfree** [comment]
@tangjeff0 Try a single quote between `%SENTRY_DSN%.`

 `.\lein run -m shadow.cljs.devtools.cli --npm compile main renderer --config-merge "{:closure-defines {athens.core/SENTRY_DSN '%SENTRY_DSN%'}}"`

image

**Comment by tangjeff0** [comment]
@juniusfree you can actually test this on your fork too.

1. Make sure your GitHub Actions are on ([yours](https://github.com/juniusfree/athens/actions) appear to be off)
1. Modify your `build.yaml`
1. Push to GitHub to start a new Action
1. If the compile step works, you should get what you just sent over

**Comment by juniusfree** [comment]
@tangjeff0 https://github.com/athensresearch/athens/pull/628

**Pull request merged**
