### PR TITLE
fix: windows sentry variable

### PR DESCRIPTION
**Pull request by juniusfree**
fix windows sentry variable https://github.com/athensresearch/athens/pull/623

https://github.com/juniusfree/athens/runs/1868201203?check_suite_focus=true

### CODE REVIEW

**Comment by tangjeff0** [comment]
It looks like the latest build, `d18ba1e`, failed: https://github.com/juniusfree/athens/actions/runs/556869285

Single quotes or double quotes?

**Comment by juniusfree** [comment]
The first command that you made is correct. This is what I get on my local and the JS build is working.
image

I'm checking why the other test failed.

**Comment by juniusfree** [comment]
@tangjeff0 All builds passed now https://github.com/juniusfree/athens/runs/1879603628?check_suite_focus=true

For future reference: Windows build is using Powershell, not Cmd.exe.

To escape special characters in Powershell: https://www.rlmueller.net/PowerShellEscape.htm

**Comment by tangjeff0** [comment]
> For future reference: Windows build is using Powershell, not Cmd.exe.

> To escape special characters in Powershell: rlmueller.net/PowerShellEscape.htm


Very useful information. Thanks @juniusfree

**Pull request merged**
