### PR TITLE
enhance(all-pages): hide empty block bullets in all pages view

### PR DESCRIPTION
**Pull request by shanberg**
- Slightly refactored styles in `all-pages` table for easier dev usability
- Fixed some typos in `all-pages` styles, restoring some minor visual polish
- Decreased opacity of block marker bullets in block preview in all-pages items
- Hide empty blocks in all-pages block previews (solving part of #1030)

### CODE REVIEW

**Review by tangjeff0 — APPROVED** [review]
1. Do you think we should render markup
image

2. Do you think we should paginate? The reason we don't is that datalog queries are such that querying for all `n` pages takes the same amount of time as querying for 5 pages. However, rendering all the DOM components is still quite expensive, which is why this can be slow.

**Comment by shanberg** [comment]
> 1. Do you think we should render markup
Yes, but I want to use this as an opportunity to think about how to separate block-level markup (headings, embeds, images, todos) from inline markup (bold, italic, links). I think we should render inline markup, but not block markup.

> 2. Do you think we should paginate?
Paginating is rational here because the list is unbounded, but I'd prefer to virtualize the list instead, if possible.

**Comment by tangjeff0** [comment]
What does virtualize the list mean?

**Comment by shanberg** [comment]
@tangjeff0 render only what's visible:
- https://github.com/bvaughn/react-window
- https://react-window.vercel.app/#/examples/list/fixed-size

This is probably a good approach for cases where we can provide our own on-page search, like the All Pages list, and not a good approach for rendering actual pages, because ctrl-f search won't work if the content isn't in the DOM.

**Pull request merged**
