### PR TITLE
feat(block-ref): shift + "Drag'n'Drop" to copy block uid

### LINKED ISSUE #572: feat(block-ref): Ctrl + "Drag'n'Drop" to copy block uid
Similar to Roam, the ability to Drag'n'Drop a Block while pushing the Ctrl-key could create a block reference for the selected block.

### PR DESCRIPTION
**Pull request by psidiumcode**
close #572

### CODE REVIEW

**Comment by psidiumcode** [comment]
The following PR enables creating block links uppon drag'n drop while pressing the `shift` key. 

https://user-images.githubusercontent.com/81385607/112547648-ae756380-8dc3-11eb-8edb-e4c4fc8e4934.mov

Note that the key used is the `shift` key, not the `ctrl` which is requested in the issue.

**Steps**

Create events for when blocks are dropped as reference links:

- `:drop-link/child`
- `:drop-link/same`
- `:drop-link/diff`

These are similar to the regular drop events, with the difference that the do not retract the block that is being dragged and instead creates a new block with `(( block-uid ))` as the content.

Create event triggers:

The events are triggered when a bullet is dropped, it uses the html property `DataTransfer.effectAllowed` with value `link` to represent a reference drag. 
When a block is dragged with the shift key pressed (detected using the `MouseEvent.shiftKey` html property), the `DataTransfer.effectAllowed` is set to `link`, otherwize it is set to `move`.

**Further improvements**

There is a lot of code repetition, specially in the drop events, while it is probably good to have the regular block drop and the block link drop as separate events, the code could improved by creating a generic function and passing the required arguments for the drop functions.

**Problems encountered**

The `shift` key was used because using any other key `ctrl`, `cmd` did not allow the bullet to be dropped. After releasing the mouse button while holding down the key, the bullet would return to it's original place. This is probably a style or similar which I could not find.

**Comment by tangjeff0** [comment]
Hello @psidiumcode. Very impressive first PR. I used `ctrl` and it worked on Linux. Perhaps this is a Mac issue?

Second, do you intend to sign the CLA or no?

**Comment by psidiumcode** [comment]
1. It could be a Mac issue with Electron, I found this old issue with the `DataTransfer.effectAllowed` property that mentions a similar behaviour to what I experienced https://github.com/electron/electron/issues/7207. A good way to test this would be to create a simple Electron project with draggable elements using the `DataTransfer.effectAllowed` properties like in this example: https://codepen.io/simoncodrington/pen/rOqPQV, to test the behaviours on all platforms.
2. The CLA is now signed

**Comment by tangjeff0** [comment]
> It could be a Mac issue with Electron, I found this old issue with the DataTransfer.effectAllowed property that mentions a similar behaviour to what I experienced electron/electron#7207. A good way to test this would be to create a simple Electron project with draggable elements using the DataTransfer.effectAllowed properties like in this example: codepen.io/simoncodrington/pen/rOqPQV, to test the behaviours on all platforms.

Sounds good - I'll test this using your suggestion as well as on my Mac this week.

**Comment by TillScout** [comment]
Nice, I have always hoped for this!
As a suggestion for improvement: Maybe add an additional modifier for creating a block embed.

**Comment by tangjeff0** [comment]
After, testing this on my M1 Mac, it indeed does not work when replacing `shiftKey` with `ctrlKey`, `metaKey`, or `altKey`.


`shift` is acceptable for now! (Not a big deal, but the original feature request #572 says to use `ctrl`. For Mac in Roam, it is `alt`.) @psidiumcode not sure how you want to get paid out for this bounty. DM me on Discord or email jeff@athensresearch.org. We can also do crypto now.

**Pull request merged**
