### PR TITLE
docs: Add badges to README

### PR DESCRIPTION
**Pull request by nthd3gr33**
TODO:
- [x] Decide if we should have badges or not
- [x] Decide on badges that should be removed
- [x] Decide if other badges should be added (source: https://shields.io/)
- [ ] implement changes

### CODE REVIEW

**Comment by itsrainingmani** [comment]
I think we should definitely atleast have badges for the build status of the latest commit to `master`. That way anyone viewing the repository can see that information without having to look for it.

**Comment by alaq** [comment]
I like it a lot @nthd3gr33! 

Is it the right place for them though? Usually they're right under the title (see [this random repo](https://github.com/reduxjs/redux-toolkit) for example). Is there a reason we don't have a title header on the README? It's especially useful with that many files at the root level.

**Comment by tangjeff0** [comment]
+1 for `build` passing badge. +1 for title and better location.

The only badges I really want are the build badge, Twitter badge with # of followers, and Discord badge if there is one. Also, please use markdown formatting where possible for the links, like the current Twitter and Discord SVGs

I'll rename our main CI script back to `build`.

**Comment by nthd3gr33** [comment]
Made the requested changes. Let me know if anything else should be done.

**Pull request merged**
