### PR TITLE
chore(electron): update from 9 to 11

### PR DESCRIPTION
**Pull request by tangjeff0**
- should automatically create `darwin-arm64` build which is for M1 Mac.
- #708

resources
- https://github.com/electron-userland/electron-builder/issues/5402#issuecomment-726577487
- https://github.com/electron-userland/electron-builder/issues/5392 

Having some trouble here. Keep on getting `Unrecognized symbol error` seeming to stem from a python file. Tried the `patch-package` approach and error still exists.

To clarify, the problem is with `electron-builder`, not `electron`. There are a few other cross-platform builders for electron that do seem to more up to date.

### CODE REVIEW

**Comment by tangjeff0** [comment]
Seeing if downloading and installing Xcode will make a difference on my M1

**Comment by sboesen** [comment]
I think the version of `electron-builder` you tried (22.9.1) does not include the latest `mac_alias`, see my other comment in https://github.com/athensresearch/athens/issues/708. 22.10.0+ includes the fix, see [commit at tag 22.10.0](https://github.com/electron-userland/electron-builder/tree/3bf31c1e84460c57b90893ce6544f84a0c2c9baa/packages/dmg-builder)

**Comment by tangjeff0** [comment]
@sboesen hadn't tried updating builder yet! If someone with an m1 manages to build, I'll split the bounty between you two. If I get to it, I'll just give the bounty to you.

**Comment by tangjeff0** [comment]
Able to build now! @sboesen

**Comment by sboesen** [comment]
@tangjeff0 Great to hear that fix worked!

**Comment by tangjeff0** [comment]
Do you want to submit to get the bounty for https://gitcoin.co/issue/athensresearch/athens/708/100024940?

**Comment by sboesen** [comment]
Thank you - I just marked work as submitted with your commit as a reference. Please let me know if I need to change anything!

**Comment by tangjeff0** [comment]
Think that's it. Gonna make sure it builds and deploys at https://github.com/athensresearch/athens/runs/2037107204?check_suite_focus=true then will approve.

**Comment by tangjeff0** [comment]
Looks good!

**Comment by sboesen** [comment]
Fantastic, thanks so much!

**Pull request merged**
