### PR TITLE
doc(backend): start architecture decision record for backend

### PR DESCRIPTION
**Pull request by agentydragon**
Iterating on this based on conversation with Abhinav and Matei.

Abhinav has been working on a Datahike backend with a shared server and always-assumed-online clients communicating over websocket. I think it would make sense to think a bit more about alternatives, because there might be options that could give us more for less buck.

- [ ] Add section about distributing/updating the server

### CODE REVIEW

**Comment by agentydragon** [comment]
I'm probably going to add a bunch of commits to the branch, I assume it'll get squashed on merge.

**Comment by jsmorabito** [comment]
just consolidated all docs to this repo, can you make this pr there?

**Comment by tangjeff0** [comment]
This is a different sort of document then the others. This might be better under a `specs/` folder, but still in handbook.

**Comment by tangjeff0** [comment]
There may be a better home for this document.

**Pull request closed without merging**
