### PR TITLE
All pages date format

### PR DESCRIPTION
**Pull request by estellerostan**
This is my first PR to improve datetime format for `Created` and `Modified` columns, based on the UI showed in #100.
It uses `juxt/tick`, the chosen date library as discussed in the issue.

Some choices I made:
- The am/pm marker is simply put to lower case but this [SO answer](https://stackoverflow.com/questions/13581608/displaying-am-and-pm-in-lower-case-after-date-formatting/13581910#13581910), although not the accepted best answer, says that it is not the correct way to do it in Java with the old `SimpleDateFormat`. I went with it anyway because:
1. Athens runs in the browser so the date input is always AM/PM and thus it doesn't have the problem mentioned in the following SO comment:
> [...] some phones display AM/PM, others display a.m./p.m. 
2. I couldn't find the equivalent of `DateFormatSymbols` for Java 8 `DateTimeFormatter`

- Localization: the previous code had a JS call to Date's [`toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) which according to the docs says that the default locale and the default time zone are en-US locale with time zone America/Los_Angeles. So localization was not implemented for Athens. Can someone correct me if I'm wrong? And it is not in the specs per se but is localization needed?

I am a Clojure beginner here to learn so comments are more than welcome!

### CODE REVIEW

**Comment by tangjeff0** [comment]
Hi @estellerostan , wonderful job! I'm working on setting up automated deploys this week. In the meantime, could you try deploying your fork on Github pages so we could see it live? Instructions are here: https://github.com/athensresearch/athens/blob/master/CONTRIBUTING.md#deploying-athens-and-devcards

**Comment by estellerostan** [comment]
Forgot to mention it, already deployed and available at https://estellerostan.github.io/athens/ !

**Comment by tangjeff0** [comment]
Great job @estellerostan  :)

**Comment by nthd3gr33** [comment]
Way to go @estellerostan! Congratulations 🎉

**Pull request merged**
