### PR TITLE
refactor: remove posh, use datascript for queries, use r/track for query subscription

### PR DESCRIPTION
**Pull request by juniusfree**
Restarting my work from https://github.com/athensresearch/athens/pull/1167

**Problem**
1. Performance issues with `posh`
2. Inefficient deref-ing https://github.com/athensresearch/athens/pull/1167#pullrequestreview-663979793

**Solution**
1. Remove posh and use pure datascript
2. Use `reagent.core/track` to improve performance. Refer to ["The track function"](https://github.com/reagent-project/reagent/blob/master/doc/ManagingState.md#the-track-function) for the list of performance improvement when using `track`.

### CODE REVIEW

**Comment by tangjeff0** [comment]
Thanks so much for sharing the link to the [Managing State](https://github.com/reagent-project/reagent/blob/master/doc/ManagingState.md) docs. I actually haven't used any of these functions yet -- `make-reaction`, `reaction`, `cursor`, `track`, `wrap`. @neotyk please let us know if @juniusfree is on the right track (lol).

**Comment by arthurbarroso** [comment]
It is also possible to use [`reg-sub-raw` from re-frame](https://day8.github.io/re-frame/Subscribing-To-External-Data/). Not sure it is needed tho.
```clojure
(re-frame/reg-sub-raw
 ::fetch-notes
 (fn [_ [_ query]
   (ratom/make-reaction #(d/q query @database))))
  ```

**Comment by arthurbarroso** [comment]
It is also possible to use [`reg-sub-raw` from re-frame's API](https://day8.github.io/re-frame/Subscribing-To-External-Data/#some-code). If we want to.
```clojure
(defn get-notes [] (d/q
                    '[:find ?title ?date ?e
                      :where
                      [?e :title ?title]
                      [?e :date ?date]]
                    @database))
                    
 (re-frame/reg-sub-raw
 ::fetch-notes
 (fn [_]
   (ratom/make-reaction get-notes)))
   

(defn componnet []
  (let [n-notes (re-frame/subscribe [::subs/fetch-notes])]
    [:div
     (map (fn [[title date entity]] 
       [:div {:key (str title entity)} (str title " -> " date " -> " entity)]) @n-notes)]))

 ```

**Comment by juniusfree** [comment]
@arthurbarroso That might be a better solution. The subscription on the components will be more readable because it's consistent with the other re-frame subscriptions.

**Comment by arthurbarroso** [comment]
> @arthurbarroso That might be a better solution. The subscription on the components will be more readable because it's consistent with the other re-frame subscriptions. I'll read more about it.

Let me know if you need any help with this. The current PR looks nice btw.

**Comment by juniusfree** [comment]
@arthurbarroso I let you know if I have questions. I'm just waiting for the advice from the core team.

**Pull request closed without merging**
