### PR TITLE
Improve sidebar tasks widget

### PR DESCRIPTION
**Pull request by shanberg**
Major
- Task status can be changed from the tasks widget
- Sidebar footer is sticky, so always appears on screen

Minor
- Number of incomplete tasks assigned to me shown per page
- Don't show the % complete on pages because it’s unclear what 100% means (my tasks vs all tasks on that page)
- Improved layout and options for tasks display settings/filter control
- Filter out pages with all tasks completed
- Task appear/disappear more smoothly

### CODE REVIEW

**Review by filipesilva — CHANGES_REQUESTED** [review]
I see an error when using in PKM mode:
- open the vercel url
- make a bullet with text
- convert to task

```
react_devtools_backend.js:4026 TypeError: Cannot read properties of null (reading 'D')
    at u9a (app.js:8316:427)
    at Function.<anonymous> (app.js:8878:255)
    at Eba (app.js:5058:459)
    at Dba (app.js:5058:380)
    at Cba (app.js:5058:295)
    at Qg (app.js:5064:122)
    at eOa (app.js:6432:49)
    at app.js:6433:466
    at GNa (app.js:6400:351)
    at g._run (app.js:6415:260)
```

**Comment by shanberg** [comment]
@filipesilva I'm only seeing that issue on the Vercel build, not when using the in-memory graph locally. Any idea why that could be?

**Comment by filipesilva** [comment]
I think the reason it appears on vercel but not locally is related (but not wholly attributed to) the feature flags.

**Comment by filipesilva** [comment]
Fixed the previous error

**Review by filipesilva — APPROVED** [review]

**Pull request merged**
