### PR TITLE
Fix: clj-kondo linter warnings

### LINKED ISSUE #39: Resolve linter warnings
[clj-kondo](https://github.com/borkdude/clj-kondo) is helping us to keep code quality high. Right now, there are still many warnings. Let's fix this. Current output can be viewed [here](https://github.com/athensresearch/athens/runs/656191957#step:4:1)

If everything is resolved, the message here will disappear:
https://github.com/athensresearch/athens/runs/656191957#step:4:46

After resolving this, we can configure the linter to fail the build.

### PR DESCRIPTION
**Pull request by yqrashawn**
resolve issue #39

### CODE REVIEW

**Comment by jeroenvandijk** [comment]
@yqrashawn Looks good! Great job :) I think we can remove the unused namespaces. I've verified that the app still works ([artifact here](https://github.com/athensresearch/athens/pull/42/checks?check_run_id=658297848))

I'll leave the merging to @tangjeff0. We still need to figure out the review flow

**Comment by yqrashawn** [comment]
> We still need to figure out the review flow

Maybe we can add [vercel](https://vercel.com/) to ease the review effort? 
I can experiment with it at my fork first. @jeroenvandijk

**Comment by tangjeff0** [comment]
Hi @yqrashawn, great idea! I believe @jeroenvandijk is working on another software project that is similar to Vercel/Zeit. We should try both of them out.

**Comment by jeroenvandijk** [comment]
@yqrashawn Go for it! Like @tangjeff0 said I am working on something to be able to easily put things live, but I'm not sure if that will cover all the use cases of Vercel and I'm also not certain about the timeline. So if you want to try it out, that would be great!

**Pull request merged**
