### PR TITLE
fix(enter/tab): do not apply changes to previous line when fast keystrokes 

### LINKED ISSUE #602: fix(input): pressing Enter and then pressing tab /shift+tab results in the changes being applied to the previous line
**Problem**
After pressing enter to go to a new line and then pressing tab / shift+tab the tabbing goes to the previous line from which you pressed enter from.

**Screenshots/Demo**

https://user-images.githubusercontent.com/77367499/106806762-58433a00-6636-11eb-82da-93460fc9bc0d.mp4

This issue has a reproductivity rate that seems tied to how fast you are trying to make changes to the new line you are on.

**Athens Version**
1.0.0-BETA.33

### PR DESCRIPTION
**Pull request by neotyk**
Fixes #602 

Enter actions where unnecessarily delayed.

This undoes patch to fix race condition when Enter is pressed and
blocks are created too fast.

At the same time it introduces solution to continuous Enter,
by ignoring Enter until blur event fires.
No more race condition.

Please test some crazy Enter usage.

### CODE REVIEW

**Comment by tangjeff0** [comment]
Holding enter creates line breaks: https://www.loom.com/share/7fa9e258da4d4dd6ba81195dae71238e

**Comment by neotyk** [comment]
Can't reproduce it locally on Mac.

Maybe we could rate limit enter?

So dispatch 1st enter when pressed and denounce for next 50ms. This would be similar to what we had, but would dispatch 1st Enter event immediately.

This is going to be a bit problematic because different text areas receive :on-key-down.

For some reasons :on-key-up is not getting triggered.

**Comment by neotyk** [comment]
@tangjeff0 can't reproduce locally on Mac, can you please test with these changes on Linux?

**Comment by tangjeff0** [comment]
Rate limiting works, but indent/unindent have a small bug. Textarea value is copied to a new block on quickly pressing enter and tab.

https://www.loom.com/share/0010be7543f14607a9572be32470c228

**Comment by neotyk** [comment]
Nice catch, let me see if I can reproduce it.

**Comment by neotyk** [comment]
@tangjeff0 Reproduced locally

**Comment by neotyk** [comment]
Pushed fix to "copy" bug.
[Enter] and [Tab] when pressed very fast are registered on textarea of starting block.
After handling [Enter], `:editing/uid` is already pointing to new block, but the [Tab] event was registered in starting block.
I've put a safeguard to not process key events from textarea that is not registered for `:editing/uid`.

**Pull request merged**
