### PR TITLE
fix(auto-complete-enter): correctly handle search/index everywhere. close #1220

### LINKED ISSUE #1220: message=Uncaught Error: Index argument to nth must be a number. source=file:///Applications/Athens.app/Contents/Resources/app.asar/resources/public/js/compiled/renderer.js lineno=282 colno=483 error=Error: Index argument to nth must be a number.
**Problem**

Highlight some words and click [[ to create a new page followed by {enter}

That's when I get the error

message=Uncaught Error: Index argument to nth must be a number.
source=file:///Applications/Athens.app/Contents/Resources/app.asar/resources/public/js/compiled/renderer.js
lineno=282
colno=483
error=Error: Index argument to nth must be a number.

I am on a MacBook Pro M1

**Screenshots/Demo**
CleanShot 2021-05-23 at 15 20 58@2x

**Athens Version**
Version 1.0.0-beta.82 (1.0.0-beta.82)

### PR DESCRIPTION
**Pull request by datokrat**
close #1220

### CODE REVIEW

**Comment by datokrat** [comment]
I updated the re-frame-10x dependency since it was updated today and the `deps-check` failed. As far as I can tell after trying the new version out, it's still working.

**Comment by tangjeff0** [comment]
What is your Discord @datokrat ?

**Review by tangjeff0 — CHANGES_REQUESTED** [review]
Doesn't seem like this leads to expected behavior. Pressing enter should auto-complete, but it just removes everything after the first double brackets.

Demo: https://www.loom.com/share/90df2eef76ad45f1b088542fb87e3b84

**Comment by datokrat** [comment]
This pull request just fixes the index bug, the autocomplete bug is fixed by #1219. I think I will just merge this commit into #1219, since both fixes are related. Then it should work.

> What is your Discord @datokrat ?

I'm "Paul R (datokrat)" # 5132.

**Comment by tangjeff0** [comment]
Would be a good idea to merge into one PR @datokrat !

**Pull request closed without merging**
