### PR TITLE
feat(graph): local-graphs and view customization

### PR DESCRIPTION
**Pull request by arkRedM**
https://www.loom.com/share/b3f16aa7c4084c69b4f47a0e03f7bf65

I am not seeing a perf issue for my current graph, although if it's leading to a bad ux, I can include it in this one or come back to it later.

Added docs based on community call discussion. I think incrementally adding docs from each pr(where code has been added or modified) is better than out-of-context adding of docs.

### CODE REVIEW

**Comment by arkRedM** [comment]
Strangely my local lint is ignoring with-let(as expected) -- not sure why this is failing here.

**Comment by tangjeff0** [comment]
@neotyk updated `cljstyle` here. Maybe that's it? https://github.com/athensresearch/athens/pull/726/files?file-filters%5B%5D=No+extension

**Comment by arkRedM** [comment]
I think it's only related to lint(clj-kondo)

**Comment by tangjeff0** [comment]
Taking a look

**Comment by borkdude** [comment]
Instead of ignoring  `r/with-let` bindings, I suggest adding the config `{:lint-as {reagent.core/with-let clojure.core/let}}`.

**Pull request merged**
