### PR TITLE
fix(parser): parse bare urls #549

### LINKED ISSUE #549: Parse bare links
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

Athens does not appear to parse "bare" links (I am not sure if this is the correct term) as such. In particular, I cannot click to open them.

**Expected Behavior**

Bare links will be recognized and rendered as something I can click to open.

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: 1.0.0-beta.25
- browser: Firefox 84.0.2
- JVM: unsure
- node.js: unsure

**To Reproduce**

- paste a bare link into a block (e.g. `https://github.com/athensresearch/athens/` -- note that it is just the link, without using the markdown link syntax)
- go to a new block such that the block containing the bare link is rendered
- note that the link is just displayed as text, rather than as an entity that can be clicked to open

**Screenshots**

[ Particularly helpful for UI bugs. ]

### PR DESCRIPTION
**Pull request by arkRedM**
close #549

### CODE REVIEW

**Comment by tangjeff0** [comment]
Awesome stuff. Can you write a test for this? @arkRedM

**Review by tangjeff0 — CHANGES_REQUESTED** [review]
@arkRedM

Part 1 review: https://www.loom.com/share/64f6d6131ae142efb8d60fb39c55a2de
Part 2 review: https://www.loom.com/share/3741eff953ba4dfdb48d161e77932499

**Comment by arkRedM** [comment]
I've decoupled `url-link-url` and `url-raw`. This currently solves the raw links.
Ideally, I think these can be combined(both have the same form and function -- url and text representing url)  ----- something to look out for in future changes.

**Review by tangjeff0 — COMMENTED** [review]
Well done @arkRedM, PR 2 done! :muscle:

**Review by tangjeff0 — APPROVED** [review]

**Pull request merged**
