### PR TITLE
fix: linked reference should show the formatting

### LINKED ISSUE #594: Linked References should show correct formatting.  Not markdown
When linked references are shown in the sidebar, they could be rendered accordingly as their markdown dicatates.  It would add better visual experience if the below screenshot showed the below in **BOLD** instead of wrapped in ** **

image

### PR DESCRIPTION
**Pull request by juniusfree**
fix #594

before:
image

fixed:
image

### CODE REVIEW

**Review by lambduhh — APPROVED** [review]
lgtm

**Review by tangjeff0 — COMMENTED** [review]
This was more complex than it seemed, but accepting the changes for now, with my own additional change. See https://www.loom.com/share/a9034ce06a544203b6a1bb9a7fc84896

**Comment by juniusfree** [comment]
@tangjeff0 Thanks for the feedback! I missed the issue on `white-space` because I focused on the right sidebar only. I should have checked the other components that use the linked reference component.

And for the parsing of block/page title, I also observed that one. I'll create a separate PR for that.

**Comment by tangjeff0** [comment]
I believe `white-space` would've had the same issue on right sidebar. I don't think it's the location (nested child block, linked refs, or right sidebar), but it's wherever there are breadcrumbs and you could use `parse-and-render`.

**Pull request merged**
