### PR TITLE
fix(blocks): links made clickable, z-index clean up #772

### PR DESCRIPTION
**Pull request by arkRedM**
https://www.loom.com/share/3b3d566401eb45a38e8ea63e74c309e2

This issue forced to fix a root issue about how z-index is handled in too many places.  This was well buried inside the hierarchy. In the loom, I tried to explain the logic for z-index, textarea and block interactions and can probably act as a reference. Cut down a good amount of hacky code with this 😌

### CODE REVIEW

**Comment by tangjeff0** [comment]
Doesn't seem to work for Linked Refs (or TODOs inside Linked Ref).

**Comment by arkRedM** [comment]
> Doesn't seem to work for Linked Refs 
Hey @tangjeff0 can you check again? I am unable to reproduce this issue. 
One theory is stylefy doesn't refresh completely even when changed(some caching at lib level)
Try and reload(CMD+R) when you switch to the branch or open a new window altogether

**Comment by tangjeff0** [comment]
CACHE IS KING

**Comment by tangjeff0** [comment]
I don't think clicking TODO/DONE works though.

**Pull request merged**
