### PR TITLE
enhance(parser): Add LaTeX support

### LINKED ISSUE #575: Latex Maths
$$ for Latex Maths (like in Roam...)

### PR DESCRIPTION
**Pull request by neotyk**
closes #575

### CODE REVIEW

**Comment by tangjeff0** [comment]
Recommend linting/styling/testing locally. It's faster than waiting for CI. https://github.com/athensresearch/athens/blob/master/CONTRIBUTING.md#running-ci-scripts-locally

**Comment by neotyk** [comment]
Can't seem to satisfy `lint` and `style` checks at the same time.

**Comment by tangjeff0** [comment]
Ah, yeah, that happens sometimes when importing npm packages, which use quotes. Guessing kondo and cljstyle look at the quotes differently.

Something like this might fix it: https://github.com/athensresearch/athens/blob/master/src/cljs/athens/views/graph_page.cljs#L1

Otherwise, I can take a look at this tomorrow. Functionality more important than linting.

**Comment by neotyk** [comment]
I've unnecessarily upgraded cljstyle. Let me know I can revert it.

**Pull request merged**
