### PR TITLE
enhance(linked-refs): sort references by newest first

### LINKED ISSUE #728: enhance(linked-refs): sort references by newest first
Please search our GitHub and Discord to see if your feature has already been requested!
References, both linked and unlinked are shown chronologically. However, I would find more useful if they were sorted "newer first" instead of the current behaviour "older first"
in discord: https://discord.com/channels/708122962422792194/800439780910563358/815988756913324042

Athens Version
1.0.0-BETA.47

### PR DESCRIPTION
**Pull request by sboesen**
Fixes #728, sorts references by newest note ID instead of oldest ID.

### CODE REVIEW

**Comment by tangjeff0** [comment]
This is a partial solution. What about for non-date pages, where the `:block/uid` is random?

What would it look like to add different sorts like in #669?

**Comment by sboesen** [comment]
Good call outs - it does appear that complete implementation of this issue is blocked on implementation of #669, or will require further edits after that's complete.

**Comment by tangjeff0** [comment]
I wouldn't say it's blocked. Both of can try to figure out sorting independently!

**Comment by sboesen** [comment]
> What about for non-date pages, where the :block/uid is random?
Currently it's sorted by `block/:id` which appears to handle showing new non-date pages first just fine, see screenshot:

Screen Shot 2021-03-08 at 9 38 20 AM

>I wouldn't say it's blocked. Both of you can try to figure out sorting independently!
If we come up with the same implementation it wouldn't be blocked, agreed! Trying to minimize throwaway work.

**Comment by tangjeff0** [comment]
There should also probably be a switch to hide date pages. What do you think @arkRedM @dauberd

**Comment by sboesen** [comment]
So I think the "newest note sort" commit does cover use case as described in this issue after rereading the thread and comments.

> What would it look like to add different sorts like in #669?
I think we'd need new UI elements to allow toggling sorting of various attributes on linked reference pages, on #669 it's pretty clear that you can click the "title", "links", "body" etc headings and it might sort the notes, currently the Linked References notes don't have anything like that.

**Comment by tangjeff0** [comment]
I'm not sure how your implementation works. `:block/id` is not used anywhere in the codebase!

**Comment by sboesen** [comment]
Oh geez, looks like I'm doing page ID when I meant block ID, and yeah, that's not a thing. Back to the drawing board, sorry for the false start here!

**Comment by sboesen** [comment]
So I tested and my change actually appears to do what we want as is (not including the proposed feature of toggling to show/hide date notes):

Screen Shot 2021-03-08 at 10 42 55 AM

Currently it is ordered by the block/page ID in descending order, which results in the latest block displaying first. After editing "older page newer ref" (which was created before "new page older ref") to add a link to `[[Index]]` it appears at the top.

**Comment by sboesen** [comment]
Added new commit with the same behavior described/in screenshot above, but using `:db/id` which actually makes sense. I actually don't know how `:block/id` worked, but it did? Still learning :D

**Review by tangjeff0 — APPROVED** [review]

**Pull request merged**
