### PR TITLE
fix: arrow down key function in page title and block page title #501

### PR DESCRIPTION
**Pull request by juniusfree**
Fix for #501

Page Title
page-title

Block Page Title
block-page-title

### CODE REVIEW

**Comment by juniusfree** [comment]
@tangjeff0 

1. I'm not entirely sure with this particularly with the use of `textarea-key-down` so let me know your thoughts on that.
2. Shift+Enter broke on this. Should I create a separate PR for that or should I include it here?

Thanks.

**Comment by tangjeff0** [comment]
Wow, I'm honestly so impressed with the progress you're making!

The code in `db.cljs` looks promising.

I see you replaced `handle-key-down` with `textarea-key-down`. This is a good intuition, but basically we just need to borrow parts of `textarea-key-down` into `handle-key-down` rather than using it entirely. The reasoning here is that we only need partial arrow-key functionality, but `textarea-key-down` does _a lot_ of stuff for blocks that we don't need.

- Copy a lot of the code from `handle-arrow-key`. https://github.com/athensresearch/athens/blob/00a6f3a2e997fd3389dcd96238fb53bcbdad319e/src/cljs/athens/keybindings.cljs#L299-L308 https://github.com/athensresearch/athens/blob/00a6f3a2e997fd3389dcd96238fb53bcbdad319e/src/cljs/athens/keybindings.cljs#L336-L341
- Copy the `get-caret-position` logic. You're using atoms and state here, which might be new to you. https://github.com/athensresearch/athens/blob/00a6f3a2e997fd3389dcd96238fb53bcbdad319e/src/cljs/athens/keybindings.cljs#L595-L596

Let me know if you need help or have questions. Great work @juniusfree .

**Comment by juniusfree** [comment]
@tangjeff0 Thanks for the detailed feedback. I'm learning a lot from this.

**Comment by juniusfree** [comment]
@tangjeff0 Code updated. Let me know if I get it right or not. Thanks.

**Comment by tangjeff0** [comment]
Great job @juniusfree. At this point, I would actually just import `handle-key-down` on `node-page.cljs` into `block-page.cljs`, then delete the redundant functions on `block-page.cljs`. This is a more direct example of reusing the same function in multiple places.

Two things:
- Why did you modify CSS?
- Make sure the GitHub Actions tests pass next. See https://github.com/athensresearch/athens/blob/master/CONTRIBUTING.md#running-ci-scripts-locally

**Comment by juniusfree** [comment]
Noted on the tests and `handle-key-down`. I'm still trying to figure out when to reuse a function or when to write a new one. Any tips on that?

>     * Why did you modify CSS?

`span.offsetTop` for the title is 0...
https://github.com/athensresearch/athens/blob/a1e7a304d47610ea4e5ceca45990cd770b23c6b0/resources/public/textarea.js#L135

...which resulted in the `:down` event not being called
https://github.com/athensresearch/athens/blob/00a6f3a2e997fd3389dcd96238fb53bcbdad319e/src/cljs/athens/keybindings.cljs#L339-L341

The problem why `span.offsetTop` is 0 is because the `textarea` element has the same height as the `h1` element. So I added a line-height for `h1` to make it taller than the `textarea`. I adjusted the margin as well so that the total height (content+padding+margin) of the `h1` does not change.

**Comment by juniusfree** [comment]
@tangjeff0 Code updated. Thanks for your patience and feedback. 😅

1. I used the `handle-key-down` in block_page.cljs
2. The `handle-enter` needs to be moved to node_page.cljs because `handle-key-down` is using it. 
Previously, pressing the enter key on the page title doesn't do anything. Now, it creates a new child block because of `handle-enter`. Is it the correct behavior for that?

**Comment by tangjeff0** [comment]
> I'm still trying to figure out when to reuse a function or when to write a new one. Any tips on that?

@juniusfree this is an excellent question, was hoping you would ask that. In this case, I thought the code would be exactly the same, so we could use the same function. In the previous case, the code was similar, but not enough so to use the same function.

Eventually, you build an intuition for it, but for where you're at it's just good to ask :)

> Previously, pressing the enter key on the page title doesn't do anything. Now, it creates a new child block because of handle-enter. Is it the correct behavior for that?

This is incorrect behavior. I forgot that node-page and block-page are slightly different for `enter` behavior.

**Comment by juniusfree** [comment]
@tangjeff0 I'll try to figure out your update. 😁 Do I need to do something on my end? And as always, thanks for the feedback.

**Comment by tangjeff0** [comment]
@juniusfree You can accept the PR haha. Or you can try to copy it locally and play around with it.

**Comment by juniusfree** [comment]
@tangjeff0 #501 approved. 😅 Closing this one.

**Comment by tangjeff0** [comment]
@juniusfree I think if you approved it, it would just update this branch, so I don't think closing was necessary

**Comment by juniusfree** [comment]
@tangjeff0 I was looking at the wrong page. PR merged.

**Review by tangjeff0 — APPROVED** [review]

**Comment by tangjeff0** [comment]
Great job on PR 2 @juniusfree :muscle:!

**Comment by juniusfree** [comment]
Thanks @tangjeff0!

**Pull request merged**
